"""Hardcoded lookup table mapping file extensions to (filetype, one-line description).

Sourced from Wikipedia's "List of filename extensions" pages (A-Z, 0-9).
Covers the most common developer, document, media, archive, and data formats.
"""

EXTENSION_INFO: dict[str, tuple[str, str]] = {
    "[no extension]": ("Generic", "File without a recognizable extension."),
    # --- 0-9 ---
    ".7z": (
        "Archive",
        "High-ratio compressed archive format, popular for distribution.",
    ),
    ".3gp": ("Video", "Multimedia container format for 3G mobile phones."),
    ".3g2": ("Video", "Multimedia container format for CDMA-based phones."),
    ".3ds": ("3D Model", "Legacy 3D model format used by Autodesk 3ds Max."),
    # --- A ---
    ".aac": ("Audio", "Advanced Audio Coding, a lossy compressed audio format."),
    ".accdb": ("Database", "Microsoft Access database file (2007+)."),
    ".aco": ("Graphics", "Adobe Photoshop color palette file."),
    ".ahk": ("Script", "AutoHotkey script for Windows automation."),
    ".ai": ("Graphics", "Adobe Illustrator vector artwork file."),
    ".aiff": ("Audio", "Audio Interchange File Format, uncompressed audio."),
    ".amr": ("Audio", "Adaptive Multi-Rate audio codec, used for speech."),
    ".ani": ("Graphics", "Animated Windows cursor file."),
    ".ape": ("Audio", "Monkey's Audio lossless audio compression format."),
    ".apk": ("Package", "Android application package for distribution and install."),
    ".arc": ("Archive", "Legacy compressed archive format."),
    ".arw": ("Image", "Sony Alpha RAW digital camera image format."),
    ".asax": ("Code", "ASP.NET global application file for event handlers."),
    ".ascx": ("Code", "ASP.NET user control markup file."),
    ".asf": ("Video", "Advanced Systems Format, Microsoft streaming media container."),
    ".ashx": ("Code", "ASP.NET generic handler file for HTTP requests."),
    ".asm": ("Code", "Assembly language source code file."),
    ".asp": ("Code", "Active Server Pages, legacy Microsoft server-side scripting."),
    ".aspx": ("Code", "ASP.NET web page with server-side controls."),
    ".asx": ("Video", "Advanced Stream Redirector playlist for ASF content."),
    ".au": ("Audio", "Sun/NeXT audio file format, commonly used on Unix."),
    ".avi": ("Video", "Audio Video Interleave, Microsoft multimedia container."),
    ".avif": ("Image", "AV1 Image File Format, next-gen royalty-free image codec."),
    ".awk": ("Script", "AWK scripting language program file."),
    # --- B ---
    ".bak": ("Data", "Generic backup file created by various applications."),
    ".bas": ("Code", "BASIC programming language source code."),
    ".bat": ("Script", "Batch script for Windows command-line automation."),
    ".bdf": ("Font", "Glyph Bitmap Distribution Format for bitmap fonts."),
    ".bib": ("Document", "BibTeX bibliography database for LaTeX documents."),
    ".bin": ("Data", "Generic binary data file, often a disk image or ROM."),
    ".blend": ("3D Model", "Blender project file containing scenes and assets."),
    ".bmp": ("Image", "Bitmap image format, uncompressed raster graphics."),
    ".br": ("Archive", "Brotli compressed data format, used for web content."),
    ".bz2": ("Archive", "Compressed archive using the Burrows-Wheeler transform."),
    ".bsp": ("Data", "Binary space partitioning map file for Quake-engine games."),
    # --- C ---
    ".c": ("Code", "C programming language source code."),
    ".c++": ("Code", "C++ programming language source code."),
    ".cab": ("Archive", "Microsoft Cabinet compressed archive for installers."),
    ".cbl": ("Code", "COBOL programming language source code."),
    ".cc": ("Code", "C++ programming language source code (alternative extension)."),
    ".cdr": ("Graphics", "CorelDRAW vector graphics drawing file."),
    ".cer": ("Certificate", "Security certificate file (X.509 format)."),
    ".cfg": ("Config", "Configuration file for application settings."),
    ".cgm": ("Graphics", "Computer Graphics Metafile for vector graphics exchange."),
    ".chm": ("Document", "Compiled HTML Help file, used for software documentation."),
    ".class": ("Code", "Compiled Java class file (bytecode)."),
    ".cmd": ("Script", "Windows NT command script (alternative to .bat)."),
    ".cob": ("Code", "COBOL programming language source code."),
    ".com": ("Executable", "MS-DOS executable program (COM format)."),
    ".conf": ("Config", "Configuration file for Unix/Linux applications."),
    ".cpp": ("Code", "C++ programming language source code."),
    ".cr2": ("Image", "Canon RAW version 2 digital camera image format."),
    ".cr3": ("Image", "Canon RAW version 3 digital camera image format."),
    ".crt": ("Certificate", "X.509 SSL/TLS certificate file."),
    ".crx": ("Package", "Google Chrome browser extension package."),
    ".cs": ("Code", "C# programming language source code."),
    ".csproj": ("Project", "C# project file for .NET / Visual Studio."),
    ".css": ("Code", "Cascading Style Sheet for web page styling."),
    ".csv": ("Data", "Comma-separated values tabular data file."),
    ".cxx": ("Code", "C++ programming language source code."),
    # --- D ---
    ".d": ("Code", "D programming language source code."),
    ".dae": ("3D Model", "COLLADA digital asset exchange XML format."),
    ".dart": ("Code", "Dart programming language source code."),
    ".dat": ("Data", "Generic data file, format depends on the application."),
    ".db": ("Database", "SQLite database file."),
    ".dbf": ("Database", "dBASE database table file format."),
    ".deb": ("Package", "Debian Linux software package format."),
    ".dem": ("Data", "Digital elevation model for terrain height data."),
    ".desktop": ("Config", "Linux desktop entry file for application launchers."),
    ".dgn": ("CAD", "MicroStation CAD design file format."),
    ".dicom": ("Image", "Digital Imaging and Communications in Medicine format."),
    ".dif": ("Data", "Data Interchange Format for spreadsheet exchange."),
    ".diff": ("Data", "Unified diff / patch file showing file changes."),
    ".dll": ("Library", "Dynamic-link library, shared code for Windows apps."),
    ".dmg": ("Disk Image", "Apple macOS disk image for software distribution."),
    ".dmp": ("Data", "Memory dump file, typically from a system crash."),
    ".dng": ("Image", "Adobe Digital Negative, open raw camera format."),
    ".doc": ("Document", "Microsoft Word document (legacy binary format)."),
    ".docm": ("Document", "Microsoft Word macro-enabled Open XML document."),
    ".docx": ("Document", "Microsoft Word Open XML document."),
    ".dot": ("Document", "Microsoft Word document template."),
    ".dtd": ("Code", "Document Type Definition for XML schema validation."),
    ".dvi": ("Document", "Device independent file, TeX output format."),
    ".dwg": ("CAD", "AutoCAD drawing database file."),
    ".dxf": ("CAD", "Drawing Exchange Format for CAD data interchange."),
    # --- E ---
    ".e": ("Code", "Eiffel programming language source code."),
    ".el": ("Code", "Emacs Lisp source code for Emacs extensions."),
    ".elc": ("Code", "Byte-compiled Emacs Lisp code."),
    ".elf": ("Executable", "Executable and Linkable Format, standard Unix binary."),
    ".emf": ("Graphics", "Enhanced Windows Metafile vector graphics format."),
    ".eml": ("Data", "Email message file in RFC 5322 (MIME) format."),
    ".eot": ("Font", "Embedded OpenType font format for web use."),
    ".eps": ("Graphics", "Encapsulated PostScript vector graphics file."),
    ".epub": ("Document", "Electronic Publication ebook format."),
    ".exe": ("Executable", "Windows portable executable program."),
    ".exr": ("Image", "OpenEXR high-dynamic-range raster image format."),
    # --- F ---
    ".f": ("Code", "Fortran source code (fixed form) or Forth source."),
    ".f4v": ("Video", "Flash video container format (H.264 encoded)."),
    ".f90": ("Code", "Fortran 90 free-form source code."),
    ".f95": ("Code", "Fortran 95 free-form source code."),
    ".fa": ("Data", "FASTA format for biological sequence data."),
    ".fb2": ("Document", "FictionBook XML-based ebook format."),
    ".fbx": ("3D Model", "Filmbox 3D model interchange format by Autodesk."),
    ".fish": ("Script", "Fish shell script for the friendly interactive shell."),
    ".fits": ("Data", "Flexible Image Transport System for astronomical data."),
    ".flac": ("Audio", "Free Lossless Audio Codec, open lossless audio format."),
    ".flv": ("Video", "Adobe Flash Video container format."),
    ".fnt": ("Font", "Bitmap font file for retro game engines."),
    ".fon": ("Font", "Windows system font file."),
    ".for": ("Code", "Fortran programming language source code."),
    ".frm": ("Data", "MySQL table metadata / form definition file."),
    ".fs": ("Code", "F# programming language source code."),
    # --- G ---
    ".gbr": ("CAD", "Gerber format for PCB manufacturing data."),
    ".gcode": ("Data", "G-code numerical control programming for CNC machines."),
    ".gdscript": ("Script", "Godot Engine's native scripting language file."),
    ".ged": ("Data", "GEDCOM genealogy data exchange format."),
    ".geojson": ("Data", "GeoJSON geographic data interchange format."),
    ".ggb": ("Document", "GeoGebra interactive mathematics file."),
    ".gif": ("Image", "Graphics Interchange Format, animated raster images."),
    ".gltf": ("3D Model", "GL Transmission Format for 3D scenes and models."),
    ".gml": ("Data", "Geography Markup Language for geographic features."),
    ".go": ("Code", "Go programming language source code."),
    ".gpx": ("Data", "GPS Exchange Format for waypoints and tracks."),
    ".grb": ("Data", "GRIB meteorological weather data format."),
    ".gs": ("Script", "Google Apps Script file for Google Workspace automation."),
    ".gz": ("Archive", "Gzip compressed file."),
    # --- H ---
    ".h": ("Code", "C/C++ header file for declarations and macros."),
    ".h++": ("Code", "C++ header file (alternative extension)."),
    ".h5": ("Data", "HDF5 format data file (alternative extension)."),
    ".har": ("Data", "HTTP Archive JSON format for web performance logs."),
    ".hdf": ("Data", "Hierarchical Data Format for large scientific datasets."),
    ".hdf5": ("Data", "HDF5, next-gen hierarchical data format."),
    ".heic": ("Image", "High-Efficiency Image Container, Apple's image format."),
    ".hh": ("Code", "C++ header file."),
    ".hpp": ("Code", "C++ header file."),
    ".hprof": ("Data", "Java heap dump or CPU profiling file."),
    ".hta": ("Script", "HTML Application executable for Windows."),
    ".htm": ("Document", "HyperText Markup Language (alternative extension)."),
    ".html": ("Document", "HyperText Markup Language for web pages."),
    ".hxx": ("Code", "C++ header file."),
    # --- I ---
    ".ical": ("Data", "iCalendar format for calendar event exchange."),
    ".icc": ("Config", "ICC color profile for device color management."),
    ".icns": ("Graphics", "macOS icon image format."),
    ".ico": ("Graphics", "Windows icon file format."),
    ".ics": ("Data", "iCalendar event or task file."),
    ".ifc": ("3D Model", "Industry Foundation Classes for BIM data exchange."),
    ".iges": ("CAD", "Initial Graphics Exchange Specification for CAD data."),
    ".img": ("Disk Image", "Raw disk image file."),
    ".iml": ("Project", "IntelliJ IDEA module configuration file."),
    ".inc": ("Code", "Include file, typically used for PHP or assembly."),
    ".inf": ("Config", "Windows setup information file for driver installation."),
    ".info": ("Document", "Texinfo hypertext documentation file."),
    ".ini": ("Config", "Initialization configuration file for Windows apps."),
    ".ino": ("Code", "Arduino sketch source code file."),
    ".ipynb": ("Document", "Jupyter interactive notebook for Python/data science."),
    ".iso": ("Disk Image", "ISO 9660 optical disc image file."),
    ".iss": ("Script", "Inno Setup installer script file."),
    # --- J ---
    ".j2k": ("Image", "JPEG 2000 wavelet-based compressed image format."),
    ".jar": ("Archive", "Java archive, distributes Java applications and libs."),
    ".java": ("Code", "Java programming language source code."),
    ".jl": ("Code", "Julia programming language source code."),
    ".jks": ("Certificate", "Java KeyStore for cryptographic keys and certs."),
    ".jnlp": ("Config", "Java Network Launching Protocol for Web Start apps."),
    ".jp2": ("Image", "JPEG 2000 image format."),
    ".jpe": ("Image", "JPEG image in Adobe RGB color space (Minolta)."),
    ".jpeg": ("Image", "Joint Photographic Experts Group lossy image format."),
    ".jpg": ("Image", "Joint Photographic Experts Group lossy image format."),
    ".js": ("Code", "JavaScript source code for web and server applications."),
    ".json": ("Data", "JavaScript Object Notation data interchange format."),
    ".jsonl": ("Data", "JSON Lines format, one JSON object per line."),
    ".jsp": ("Code", "Jakarta Server Pages for dynamic Java web content."),
    ".jxl": ("Image", "JPEG XL next-generation royalty-free image format."),
    # --- K ---
    ".key": ("Document", "Apple Keynote presentation file."),
    ".kicad_pcb": ("CAD", "KiCad PCB layout design file."),
    ".kicad_sch": ("CAD", "KiCad schematic design file."),
    ".kml": ("Data", "Keyhole Markup Language for geographic data (Google Earth)."),
    ".kmz": ("Data", "Compressed KML file for geographic data."),
    ".ko": ("Library", "Linux kernel module (loadable kernel object)."),
    ".kra": ("Image", "Krita native raster image project file."),
    ".ksh": ("Script", "KornShell scripting language script file."),
    ".kt": ("Code", "Kotlin programming language source code."),
    # --- L ---
    ".latex": ("Document", "LaTeX typesetting document source file."),
    ".less": ("Code", "LESS CSS pre-processor stylesheet file."),
    ".lha": ("Archive", "LHA/LHARC compressed archive format (Amiga/MS-DOS)."),
    ".lib": ("Library", "Static library file for Windows or MS-DOS linking."),
    ".lisp": ("Code", "Lisp programming language source code."),
    ".ll": ("Code", "LLVM assembly language intermediate representation."),
    ".lnk": ("Data", "Windows shortcut linking to a file or program."),
    ".lock": ("Data", "Dependency lock file for reproducible builds."),
    ".log": ("Data", "Application or system log file with timestamped entries."),
    ".lrc": ("Data", "Lyrics file for karaoke time-synced song lyrics."),
    ".lsp": ("Code", "Lisp programming language source code."),
    ".lua": ("Code", "Lua embedded scripting language source code."),
    ".lwo": ("3D Model", "LightWave 3D object file format."),
    ".ly": ("Code", "LilyPond music engraving source file."),
    ".lz": ("Archive", "Lzip compressed archive."),
    ".lzma": ("Archive", "LZMA compressed archive."),
    # --- M ---
    ".m": ("Code", "MATLAB/Mathematica script or Objective-C source code."),
    ".m2ts": ("Video", "Blu-ray BDAV MPEG-2 transport stream video file."),
    ".m3u": ("Playlist", "MP3 URL playlist file for audio streaming."),
    ".m3u8": ("Playlist", "UTF-8 MP3 URL playlist for audio streaming."),
    ".m4a": ("Audio", "MPEG-4 audio file (AAC codec)."),
    ".m4r": ("Audio", "iPhone ringtone file (AAC format)."),
    ".m4v": ("Video", "MPEG-4 video file, optionally with DRM."),
    ".ma": ("3D Model", "Autodesk Maya ASCII scene description."),
    ".make": ("Build", "Makefile for GNU Make build automation."),
    ".map": ("Data", "Map file, used by compilers for symbol mapping or game maps."),
    ".markdown": ("Document", "Markdown document (alternative to .md)."),
    ".mat": ("Data", "MATLAB MAT-file for numerical matrix storage."),
    ".mbox": ("Data", "Unix mailbox file for email message storage."),
    ".md": ("Document", "Markdown lightweight markup text file."),
    ".mdb": ("Database", "Microsoft Access database file (legacy format)."),
    ".mdf": ("Data", "Master Data File (SQL Server) or Measurement Data Format."),
    ".mel": ("Script", "Maya Embedded Language script for Maya automation."),
    ".mht": ("Document", "MIME HTML archive for saving web pages."),
    ".mid": ("Audio", "MIDI music file for synthesizer playback."),
    ".mjs": ("Code", "JavaScript ES module source file."),
    ".mka": ("Audio", "Matroska audio container file."),
    ".mkv": ("Video", "Matroska video container file."),
    ".mlx": ("Code", "MATLAB Live Script interactive document."),
    ".mm": ("Code", "Objective-C++ source code."),
    ".mo": ("Data", "Machine Object, compiled GNU gettext translation file."),
    ".mobi": ("Document", "Mobipocket ebook format, used by older Kindles."),
    ".mod": ("Audio", "Protracker module music file."),
    ".mov": ("Video", "Apple QuickTime movie container format."),
    ".mp2": ("Audio", "MPEG-1 Audio Layer 2 compressed audio file."),
    ".mp3": ("Audio", "MPEG-1 Audio Layer 3, ubiquitous lossy audio format."),
    ".mp4": ("Video", "MPEG-4 Part 14 multimedia container format."),
    ".mpeg": ("Video", "MPEG-1/2 video container format."),
    ".mpg": ("Video", "MPEG-1/2 video file (common alternative extension)."),
    ".mpp": ("Document", "Microsoft Project file for project management."),
    ".msi": ("Package", "Microsoft Windows Installer package file."),
    ".mui": ("Library", "Multilingual User Interface file for Windows localization."),
    ".mxf": ("Video", "Material Exchange Format for professional video."),
    # --- N ---
    ".nb": ("Document", "Wolfram Mathematica notebook file."),
    ".nc": ("Data", "NetCDF scientific data file or CNC instruction file."),
    ".ndjson": ("Data", "Newline-delimited JSON format."),
    ".nds": ("Data", "Nintendo DS ROM image for games."),
    ".nef": ("Image", "Nikon Electronic Format RAW camera image."),
    ".nim": ("Code", "Nim programming language source code."),
    ".nfo": ("Document", "Info file with metadata about a release or software."),
    ".nginx": ("Config", "Nginx web server configuration file."),
    ".npy": ("Data", "NumPy array binary data file for Python."),
    ".npz": ("Data", "Compressed NumPy archive of multiple arrays."),
    ".nro": ("Executable", "Nintendo Switch homebrew executable file."),
    ".nrw": ("Image", "Nikon Coolpix RAW image format."),
    ".nsi": ("Script", "Nullsoft Scriptable Install System installer script."),
    ".numbers": ("Document", "Apple Numbers spreadsheet file."),
    ".nupkg": ("Package", "NuGet package for .NET libraries."),
    # --- O ---
    ".o": ("Code", "Compiled object file, output of an assembler/compiler."),
    ".obj": ("3D Model", "Wavefront OBJ 3D geometry definition file."),
    ".odc": ("Database", "Microsoft Office Data Connection file."),
    ".odb": ("Document", "OpenDocument base, front-end database file."),
    ".odf": ("Document", "OpenDocument formula / mathematical equation file."),
    ".odg": ("Document", "OpenDocument drawing / vector graphics file."),
    ".odp": ("Document", "OpenDocument presentation file."),
    ".ods": ("Document", "OpenDocument spreadsheet file."),
    ".odt": ("Document", "OpenDocument text / word-processing document."),
    ".oga": ("Audio", "Ogg container audio file (Vorbis or Opus codec)."),
    ".ogg": ("Audio", "Ogg Vorbis compressed audio file."),
    ".ogv": ("Video", "Ogg container video file (Theora codec)."),
    ".one": ("Document", "Microsoft OneNote notebook file."),
    ".opus": ("Audio", "Opus interactive audio codec in Ogg container."),
    ".org": ("Document", "Emacs Org mode plain-text organizer and document."),
    ".osm": ("Data", "OpenStreetMap XML geographic data file."),
    ".ost": ("Data", "Offline Storage Table, Outlook offline data file."),
    ".otf": ("Font", "OpenType font format, cross-platform scalable font."),
    ".owl": ("Data", "Web Ontology Language file for semantic web ontologies."),
    ".oxt": ("Package", "Apache OpenOffice extension package."),
    # --- P ---
    ".p": ("Code", "Pascal programming language source code."),
    ".p12": ("Certificate", "PKCS#12 personal information exchange certificate file."),
    ".pack": ("Archive", "Pack200 compressed JAR file."),
    ".pages": ("Document", "Apple Pages word-processing document file."),
    ".pak": ("Archive", "Game archive file, stores assets and data."),
    ".pas": ("Code", "Pascal programming language source code."),
    ".patch": ("Data", "Patch file containing code differences."),
    ".pbm": ("Image", "Portable Bitmap, monochrome ASCII raster image."),
    ".pcap": ("Data", "Packet capture file for network traffic analysis."),
    ".pch": ("Code", "Precompiled C/C++ header for faster compilation."),
    ".pcl": ("Data", "HP Printer Command Language print job file."),
    ".pdb": (
        "Data",
        "Program database for debugging symbols (Windows) or protein structure.",
    ),
    ".pde": ("Code", "Processing visual sketch source code file."),
    ".pdf": ("Document", "Portable Document Format, cross-platform document."),
    ".pem": ("Certificate", "Privacy-Enhanced Mail, base64-encoded certificate."),
    ".pfx": ("Certificate", "PKCS#12 certificate with private key."),
    ".pgn": ("Data", "Portable Game Notation for chess game recording."),
    ".php": ("Code", "PHP: Hypertext Preprocessor scripting language source."),
    ".php5": ("Code", "PHP 5 scripting language source code."),
    ".pickle": ("Data", "Python pickle serialized object data file."),
    ".pkg": ("Package", "macOS or iOS installer package file."),
    ".pl": ("Code", "Perl programming language source code."),
    ".plist": ("Data", "Apple property list XML/binary file."),
    ".pls": ("Playlist", "Shoutcast / Icecast multimedia playlist file."),
    ".ply": ("3D Model", "Polygon File Format for 3D scans."),
    ".pm": ("Library", "Perl module library file."),
    ".png": ("Image", "Portable Network Graphics lossless raster image format."),
    ".po": ("Data", "Portable Object, GNU gettext translation file."),
    ".pom": ("Config", "Maven Project Object Model build configuration."),
    ".pot": ("Document", "Microsoft PowerPoint template file."),
    ".pp": ("Code", "Puppet manifest configuration file."),
    ".ppa": ("Document", "Microsoft PowerPoint add-in file."),
    ".pps": ("Document", "Microsoft PowerPoint slideshow file."),
    ".ppt": ("Document", "Microsoft PowerPoint presentation (legacy binary format)."),
    ".pptx": ("Document", "Microsoft PowerPoint Open XML presentation."),
    ".prj": ("Project", "Project file for various IDEs and GIS software."),
    ".pro": ("Project", "Qt project file."),
    ".properties": ("Config", "Java properties configuration file (key=value)."),
    ".proto": ("Code", "Protocol Buffers message definition file."),
    ".ps": ("Data", "Adobe PostScript page description language file."),
    ".psb": ("Image", "Adobe Photoshop large document format (over 2GB)."),
    ".psd": ("Image", "Adobe Photoshop native layered image file."),
    ".psd1": ("Script", "PowerShell module manifest file."),
    ".psm1": ("Script", "PowerShell script module file."),
    ".pst": ("Data", "Outlook Personal Storage Table for emails/calendars."),
    ".ps1": ("Script", "PowerShell script file."),
    ".pub": ("Document", "Microsoft Publisher document file."),
    ".py": ("Code", "Python programming language source code."),
    ".pyc": ("Code", "Python compiled bytecode file."),
    ".pyd": ("Library", "Python dynamic module (Windows DLL)."),
    ".pyo": ("Code", "Python optimized bytecode file (Python 2 / 3.4-)."),
    ".pyw": ("Script", "Python script that runs without a console window."),
    ".pyx": ("Code", "Cython source file for Python-C extensions."),
    # --- Q ---
    ".qif": ("Data", "Quicken Interchange Format for financial data."),
    ".qml": ("Code", "QML declarative UI language file (Qt framework)."),
    ".qoi": ("Image", "Quite OK Image Format, lossless raster image."),
    ".qrc": ("Config", "Qt resource collection file for embedded resources."),
    ".qss": ("Config", "Qt Style Sheet for application theming."),
    ".qt": ("Video", "Apple QuickTime movie format."),
    # --- R ---
    ".r": ("Code", "R programming language script for statistical computing."),
    ".r3d": ("Video", "RED Raw video file from RED digital cameras."),
    ".ra": ("Audio", "RealAudio streaming media file."),
    ".ram": ("Audio", "RealMedia metafile for streaming."),
    ".rar": ("Archive", "RAR compressed archive format."),
    ".raw": ("Image", "Raw camera sensor data image file."),
    ".razor": ("Code", "Razor view template (ASP.NET)."),
    ".rb": ("Code", "Ruby programming language source code."),
    ".rdata": ("Data", "R data file for serialized R objects."),
    ".rds": ("Data", "R serialized single-object data file."),
    ".rdp": ("Config", "Remote Desktop Protocol connection settings file."),
    ".reg": ("Config", "Windows registry import/export file."),
    ".res": ("Data", "Compiled resource file for Windows applications."),
    ".rexx": ("Script", "Rexx scripting language source code."),
    ".rkt": ("Code", "Racket programming language source code."),
    ".rm": ("Video", "RealMedia streaming media file."),
    ".rmd": ("Document", "R Markdown document for reproducible analytics."),
    ".rmvb": ("Video", "RealMedia Variable Bitrate video file."),
    ".rpm": ("Package", "RPM Package Manager, Linux software package."),
    ".rpy": ("Script", "Ren'Py visual novel script file."),
    ".rs": ("Code", "Rust programming language source code."),
    ".rss": ("Data", "RSS feed XML format for content syndication."),
    ".rst": ("Document", "reStructuredText markup file, used by Python docs."),
    ".rtf": ("Document", "Rich Text Format document with text formatting."),
    # --- S ---
    ".s": ("Code", "Assembly source code (Unix/gas syntax)."),
    ".s3m": ("Audio", "Scream Tracker 3 module music file."),
    ".sam": ("Data", "Sequence Alignment/Map format for bioinformatics."),
    ".sass": ("Code", "Sass syntactically awesome stylesheets, indented syntax."),
    ".sav": ("Data", "SPSS binary tabular data file."),
    ".sb": ("Data", "Scratch 1.x project file."),
    ".sb2": ("Data", "Scratch 2.0 project file."),
    ".sb3": ("Data", "Scratch 3.0 project file."),
    ".scad": ("Code", "OpenSCAD 3D CAD script file."),
    ".scala": ("Code", "Scala programming language source code."),
    ".sch": ("CAD", "Schematic file for EAGLE or KiCad."),
    ".scm": ("Code", "Scheme programming language source code."),
    ".scr": ("Executable", "Windows screen saver executable file."),
    ".scss": ("Code", "Sassy CSS stylesheet with SCSS syntax."),
    ".sdf": ("Database", "SQL Server Compact database file."),
    ".sed": ("Script", "Sed stream editor script file."),
    ".sf2": ("Audio", "SoundFont 2.0 sound bank file."),
    ".sh": ("Script", "Unix Bourne shell script."),
    ".shar": ("Archive", "Shell self-extracting archive (Unix)."),
    ".shtml": ("Document", "Server-side include enabled HTML file."),
    ".sig": ("Data", "Digital signature file (GPG, PGP)."),
    ".sis": ("Package", "Symbian OS installation package."),
    ".sit": ("Archive", "StuffIt compressed archive (macOS)."),
    ".sldasm": ("CAD", "SolidWorks assembly file."),
    ".slddrw": ("CAD", "SolidWorks drawing file."),
    ".sldprt": ("CAD", "SolidWorks part file."),
    ".sln": ("Project", "Visual Studio solution file for .NET projects."),
    ".slx": ("Data", "MATLAB Simulink model file."),
    ".smi": ("Data", "SAMI subtitle file."),
    ".sml": ("Code", "Standard ML source code."),
    ".snap": ("Package", "Ubuntu Snap package."),
    ".so": ("Library", "Shared object, Unix/Linux dynamically linked library."),
    ".spec": ("Config", "RPM spec file for building packages."),
    ".spin": ("Code", "Spin language source (Parallax Propeller)."),
    ".sps": ("Data", "SPSS program syntax file."),
    ".spx": ("Audio", "Ogg Speex speech audio codec file."),
    ".sql": ("Code", "Structured Query Language database query file."),
    ".sqlite": ("Database", "SQLite database file (alternative extension)."),
    ".srt": ("Data", "SubRip subtitle file for video captioning."),
    ".ssa": ("Data", "SubStation Alpha subtitle file."),
    ".st": ("Code", "SMALLTALK source code or structured text."),
    ".stc": ("Document", "OpenOffice Calc spreadsheet template."),
    ".step": ("3D Model", "STEP 3D CAD exchange format (ISO 10303)."),
    ".stl": ("3D Model", "Stereolithography format for 3D printing geometry."),
    ".stp": ("3D Model", "STEP 3D CAD model file."),
    ".sty": ("Config", "LaTeX style file."),
    ".suo": ("Config", "Visual Studio solution user options file."),
    ".svg": ("Graphics", "Scalable Vector Graphics XML-based vector format."),
    ".svgz": ("Graphics", "Compressed SVG file."),
    ".swf": ("Video", "Shockwave Flash animation file (legacy)."),
    ".swift": ("Code", "Swift programming language source code (Apple)."),
    ".swp": ("Data", "Swap file or Vim editor temporary swap file."),
    ".sxc": ("Document", "OpenOffice.org XML spreadsheet file."),
    ".sxd": ("Document", "OpenOffice.org XML drawing file."),
    ".sxi": ("Document", "OpenOffice.org XML presentation file."),
    ".sxw": ("Document", "OpenOffice.org XML text document file."),
    ".sym": ("Data", "Symbol file for debugging (various formats)."),
    ".sys": ("Config", "Windows system/configuration file or device driver."),
    # --- T ---
    ".tar": ("Archive", "Tape archive, uncompressed file bundling format."),
    ".taz": ("Archive", "Tar archive compressed with compress (.Z)."),
    ".tbz": ("Archive", "Tar archive compressed with bzip2."),
    ".tbz2": ("Archive", "Tar archive compressed with bzip2."),
    ".tcl": ("Script", "Tcl scripting language source code."),
    ".tex": ("Document", "LaTeX/TeX typesetting system source document."),
    ".tga": ("Image", "Truevision TGA raster image format."),
    ".tgz": ("Archive", "Tar archive compressed with gzip."),
    ".thm": ("Image", "Thumbnail image file generated by cameras."),
    ".tif": ("Image", "Tagged Image File Format (alternative extension)."),
    ".tiff": ("Image", "Tagged Image File Format for high-quality raster images."),
    ".tlz": ("Archive", "Tar archive compressed with LZMA."),
    ".tmp": ("Data", "Temporary file, contents may be deleted automatically."),
    ".toml": ("Config", "Tom's Obvious Minimal Language configuration format."),
    ".torrent": ("Data", "BitTorrent metainfo file for peer-to-peer sharing."),
    ".tpl": ("Data", "Template file (Smarty, Drupal, etc.)."),
    ".ts": ("Code", "TypeScript programming language source code."),
    ".tscn": ("Data", "Godot Engine text scene file."),
    ".tsv": ("Data", "Tab-separated values tabular data file."),
    ".ttc": ("Font", "TrueType font collection file."),
    ".ttf": ("Font", "TrueType font, cross-platform scalable outline font."),
    ".twb": ("Data", "Tableau workbook file for data visualization."),
    ".txt": ("Document", "Plain text file without formatting."),
    ".txz": ("Archive", "Tar archive compressed with xz."),
    ".tzst": ("Archive", "Tar archive compressed with Zstandard."),
    # --- U ---
    ".ui": ("Data", "Qt Designer user interface XML form file."),
    ".upd": ("Data", "Update file, contains software patch data."),
    ".url": ("Data", "Internet shortcut file pointing to a URL."),
    ".usdz": ("3D Model", "Universal Scene Description for AR (Pixar/Apple)."),
    # --- V ---
    ".v": ("Code", "Verilog / V (Vlang) / Rocq source code."),
    ".vb": ("Code", "Visual Basic .NET source code file."),
    ".vba": ("Code", "Visual Basic for Applications macro module."),
    ".vbs": ("Script", "VBScript scripting language file."),
    ".vcard": ("Data", "vCard electronic business card format."),
    ".vdi": ("Disk Image", "VirtualBox Virtual Disk Image file."),
    ".vhd": ("Disk Image", "Virtual Hard Disk, Microsoft virtualization format."),
    ".vhdx": ("Disk Image", "Hyper-V Virtual Hard Disk v2 format."),
    ".vmdk": ("Disk Image", "VMware Virtual Disk file."),
    ".vob": ("Video", "DVD Video Object file, MPEG-2 program stream."),
    ".vpk": ("Package", "Valve Pak, archive for Source engine assets."),
    ".vsd": ("Document", "Microsoft Visio drawing (legacy format)."),
    ".vsdx": ("Document", "Microsoft Visio Open XML drawing."),
    ".vsix": ("Package", "Visual Studio VSIX extension package."),
    ".vst": ("Image", "Truevision Vista bitmap graphics."),
    ".vue": ("Code", "Vue.js single-file component template."),
    # --- W ---
    ".wad": ("Data", "WAD archive for Doom-engine game assets."),
    ".wasm": ("Code", "WebAssembly binary executable for browser apps."),
    ".wat": ("Code", "WebAssembly text format readable representation."),
    ".wav": ("Audio", "Waveform audio file, Microsoft RIFF uncompressed audio."),
    ".wbmp": ("Image", "Wireless Bitmap image for mobile devices."),
    ".webm": ("Video", "Royalty-free WebM video container format."),
    ".webp": ("Image", "Google WebP image format, lossy and lossless."),
    ".whl": ("Package", "Python wheel binary package distribution format."),
    ".wim": ("Disk Image", "Windows Imaging Format for system deployment."),
    ".wl": ("Code", "Wolfram Language package file."),
    ".wls": ("Script", "Wolfram Language script file."),
    ".wma": ("Audio", "Windows Media Audio, proprietary audio format."),
    ".wmf": ("Graphics", "Windows Metafile vector graphics format."),
    ".wmv": ("Video", "Windows Media Video, proprietary video format."),
    ".woff": ("Font", "Web Open Font Format for web typography."),
    ".woff2": ("Font", "Web Open Font Format v2 with improved compression."),
    ".wpd": ("Document", "WordPerfect document (alternative extension)."),
    ".wsf": ("Script", "Windows Script File, XML container for multiple scripts."),
    # --- X ---
    ".x": ("Code", "Lex / Flex lexical analyzer source code."),
    ".x3d": ("3D Model", "X3D ISO standard 3D graphics file format."),
    ".xar": ("Archive", "Extensible Archive format (XAR)."),
    ".xcf": ("Image", "GIMP native image project with layers."),
    ".xhtml": ("Document", "Extensible HyperText Markup Language."),
    ".xla": ("Document", "Microsoft Excel add-in file."),
    ".xlam": ("Document", "Microsoft Excel macro-enabled add-in."),
    ".xls": ("Document", "Microsoft Excel spreadsheet (legacy binary format)."),
    ".xlsb": ("Document", "Microsoft Excel binary workbook (BIFF12)."),
    ".xlsm": ("Document", "Microsoft Excel macro-enabled Open XML workbook."),
    ".xlsx": ("Document", "Microsoft Excel Open XML spreadsheet."),
    ".xlt": ("Document", "Microsoft Excel template file."),
    ".xlw": ("Document", "Microsoft Excel workspace file."),
    ".xm": ("Audio", "FastTracker 2 extended module music file."),
    ".xml": ("Data", "Extensible Markup Language for structured data."),
    ".xmp": ("Data", "Extensible Metadata Platform for metadata embedding."),
    ".xps": ("Document", "Open XML Paper Specification, Microsoft document format."),
    ".xsd": ("Data", "XML Schema Definition for XML document validation."),
    ".xsl": ("Data", "XSL Stylesheet for XML transformation."),
    ".xslt": ("Data", "XSL Transformations for converting XML documents."),
    ".xyz": ("Data", "Molecular coordinate format for 3D molecule data."),
    ".xz": ("Archive", "XZ compressed archive using LZMA2 algorithm."),
    # --- Y ---
    ".y": ("Code", "Yacc / Bison parser generator grammar file."),
    ".yaml": (
        "Config",
        "YAML Ain't Markup Language, human-readable data serialization.",
    ),
    ".yml": ("Config", "YAML configuration file (alternative extension)."),
    # --- Z ---
    ".z": ("Archive", "Unix compress compressed file."),
    ".zig": ("Code", "Zig programming language source code."),
    ".zip": ("Archive", "ZIP compressed archive, the most widely used archive format."),
    ".zst": ("Archive", "Zstandard compressed file."),
}
